### ISSUE TITLE
Can comments also be rendered for other models?

### ISSUE THREAD

**Issue by ghost** [luciuschoi/vagrant-test#2]
I think since this is polymorphic i should be able to use it with another model. It worked well with my story model but when i implemented it to an episode model which belongs to story i was faced with an error "undefined method `episode_comments_path' for #<#<Class:0xb3ea688>:0x10f44b70>" pointing to "<%= form_for [comment.commentable, comment], remote: true do | f | %>"

**Comment by luciuschoi** [comment]
Did you add a nested routing for episode resources?
```ruby
Rails.application.routes.draw do
  ···
  resources :stories, :episodes do
    resources :comments, except: [:index, :new, :show] do
      member do
        get :reply
      end
    end
  end
···
```

I'm sorry to be late.

**Comment by ghost** [comment]
It's now working... I actually didn't get the routes nested well like you said.
Thanks.

**Comment by ghost** [comment]
Just that the cancel button on the reply form does not respond to the "cancel link" and also flash messages does not work on episode page, works on story page.

**Comment by luciuschoi** [comment]
Can I look over your codes?

**Comment by ghost** [comment]
Okay... https://github.com/Klashe/stories

**Comment by luciuschoi** [comment]
Yeap. I found out the error.
You missed to add `simple_form` gem in Gemfile and bundle install.
Additionally, after that, you should do the following command:

```shell
$ rails g simple_form:install --bootstrap
```

Finally, you modified the `comments/_form.html.erb` file as follows:

```erb
<div class="comment-form">
  <%= simple_form_for [comment.commentable, comment], remote: true do | f | %>
    <%= f.hidden_field :parent_id %>
    <div class="mb-3">
      <p><%= f.input :content, label: false, class: "form-control", placeholder: (f.object.parent_id.nil? ? 'Share your idea.' : 'Leave your reply.'), wrapper_html: { class: 'mb-1' }, input_html: { rows: 5, data:{ 'comment-id': (comment.persisted? ? comment.id : 'new') }} %></p>
    </div>
    <span id="comment_<%= comment.persisted? ? comment.id : 'new' %>_chars_counter" class="comment_chars_counter">Remaining : 255</span>
    <div class='float-right'>
      <%= f.submit "Submit Comment", class: "btn btn-sm btn-success float-xs-right", data: { disable_with: "<i class='fa fa-spinner fa-spin'></i> Submiting Comment..." } %>
      <%= link_to "Cancel", "#", 'data-reply': comment.parent_id.present?, class: 'cancel-comment-link btn btn-warning btn-sm float-xs-right ml-1' if comment.persisted? or comment.parent %>
    </div>  
    <div class="clearfix"></div>
  <% end %>
</div>
```

That't it.
Sorry to be late.

**Comment by ghost** [comment]
Oh thanks... I was thinking simple form is optional before, I'll re-adjust
my codes.

**Comment by ghost** [comment]
Did you test balakirevs's notification?

**Comment by luciuschoi** [comment]
Of course, `simple_form` gem is optional and so you can implement the same functionality without simple_form gem.
Not yet I did. I'll try as soon as possible.
