### ISSUE TITLE
How to link_to a commentable object?

### ISSUE THREAD

**Issue by ghost** [luciuschoi/vagrant-test#5]
Hi Lucius! I displayed a list of user's comments and also displayed the title what they commented on their profile page. However, i also want to link to the object they commented on, how do I generate the link?

For example I commented on a post titled "Post 1", I want to be able to like this:
comment / link_to post

This is my route

```
resources :books do
    resources :chapters
    resources :reviews
    resource :save_book, module: :books
  end

  resources :books, :chapters, :articles, :announcements do
    resources :comments, except: [:index, :new, :show] do
      member do
        get :reply
      end
    end
  end
```

Thank you!

**Comment by luciuschoi** [comment]
Hi
when  you want to navigate to the post, just refer to  comment.post.
Did I understand what you mean?

<%= link_to “Go to the post”, comment.post %>

**Comment by ghost** [comment]
Since I've comments on more than one model, I did this on the profile page
```
<% @user.comments.each do |comment| %>
    <%= comment.content %> / <%= link_to comment.commentable.title, comment.commentable %>
<% end %>
```
which outputs the links to to the commentable object.

Then I've a chapters model which is nested in the book model. Books have it's own chapters and chapters are displayed on the books show page (I have no chapters index page)... So the above link works with other models i.e articles, announcement but it's outputting incorrect link for the chapter's show page.

I need something like this 
```
http://localhost:3000/books/the-devil-who-loved-me-by-davidflo/chapters/1
```

but I'm getting this
```
http://localhost:3000/chapters/chapter-1
```

**Comment by ghost** [comment]
Secondly, I'm trying to display notifications for when comments in any of the models

My comment.rb goes like this

```
after_commit :notify_comment_created, on: [:create]
  def notify_comment_created
    return if self.commentable.blank?
    receiver_id = self.commentable&.user_id
    return if receiver_id.blank?
    # notified_user_ids = self.mentioned_user_ids || []
    # return if notified_user_ids.include?(receiver_id)

    Notification.create(
      notify_type: "comment",
      target: self,
      second_target: self.commentable,
      actor_id: self.user_id,
      user_id: receiver_id
    )
  end
```

and my notifications/_comment

```
<p class="notifications-p"><i class="fa fa-thumbs-up text-secondary"></i> <b><%= link_to notification.actor.username, main_app.profile_path(notification.actor.username) %></b> liked your <b><%= notification.second_target.class.name %>:</b> <b><%= link_to notification.second_target.title, notification.second_target %></b></p>
```

then I'm getting error
```
undefined method `announcement_path'
```

**Comment by ghost** [comment]
Thank you for responding...
